const subjects = [
    { name: "Aboriginal Studies", code: "1ABG10", stage: "1" },
    { name: "Aboriginal Studies", code: "1ABG20", stage: "1" },
    { name: "Accounting", code: "1ACO10", stage: "1" },
    { name: "Accounting", code: "1ACO20", stage: "1" },
    { name: "Australian Languages - Additional Language", code: "1ADL10", stage: "1" },
    { name: "Australian Languages - Additional Language", code: "1ADL20", stage: "1" },
    { name: "Armenian (continuers)", code: "1AEC10", stage: "1" },
    { name: "Armenian (continuers)", code: "1AEC20", stage: "1" },
    { name: "Australian Languages - First Language", code: "1AFL10", stage: "1" },
    { name: "Australian Languages - First Language", code: "1AFL20", stage: "1" },
    { name: "Agriculture", code: "1AGU10", stage: "1" },
    { name: "Agriculture", code: "1AGU20", stage: "1" },
    { name: "Albanian (continuers)", code: "1ALC10", stage: "1" },
    { name: "Albanian (continuers)", code: "1ALC20", stage: "1" },
    { name: "Ancient Studies", code: "1ANT10", stage: "1" },
    { name: "Ancient Studies", code: "1ANT20", stage: "1" },
    { name: "Arabic (continuers)", code: "1ARC10", stage: "1" },
    { name: "Arabic (continuers)", code: "1ARC20", stage: "1" },
    { name: "Australian Languages - Revival Language", code: "1ARL10", stage: "1" },
    { name: "Australian Languages - Revival Language", code: "1ARL20", stage: "1" },
    { name: "Auslan (continuers)", code: "1AUC10", stage: "1" },
    { name: "Auslan (continuers)", code: "1AUC20", stage: "1" },
    { name: "Bengali (continuers)", code: "1BEC10", stage: "1" },
    { name: "Bengali (continuers)", code: "1BEC20", stage: "1" },
    { name: "Biology", code: "1BGY10", stage: "1" },
    { name: "Biology", code: "1BGY20", stage: "1" },
    { name: "Business Innovation", code: "1BNV10", stage: "1" },
    { name: "Business Innovation", code: "1BNV20", stage: "1" },
    { name: "Bosnian (continuers)", code: "1BOC10", stage: "1" },
    { name: "Bosnian (continuers)", code: "1BOC20", stage: "1" },
    { name: "Chemistry", code: "1CEM10", stage: "1" },
    { name: "Chemistry", code: "1CEM20", stage: "1" },
    { name: "Chinese (beginners)", code: "1CHB10", stage: "1" },
    { name: "Chinese (beginners)", code: "1CHB20", stage: "1" },
    { name: "Chinese (continuers)", code: "1CHC10", stage: "1" },
    { name: "Chinese (continuers)", code: "1CHC20", stage: "1" },
    { name: "Chinese (background speakers)", code: "1CHD10", stage: "1" },
    { name: "Chinese (background speakers)", code: "1CHD20", stage: "1" },
    { name: "Chin Hakha (continuers)", code: "1CKC10", stage: "1" },
    { name: "Chin Hakha (continuers)", code: "1CKC20", stage: "1" },
    { name: "Community Studies", code: "1COM10", stage: "1" },
    { name: "Community Studies", code: "1COM20", stage: "1" },
    { name: "Croatian (continuers)", code: "1CRC10", stage: "1" },
    { name: "Croatian (continuers)", code: "1CRC20", stage: "1" },
    { name: "Child Studies", code: "1CSD10", stage: "1" },
    { name: "Child Studies", code: "1CSD20", stage: "1" },
    { name: "Creative Arts", code: "1CVA10", stage: "1" },
    { name: "Creative Arts", code: "1CVA20", stage: "1" },
    { name: "Cross-disciplinary Studies", code: "1CXD10", stage: "1" },
    { name: "Cross-disciplinary Studies", code: "1CXD20", stage: "1" },
    { name: "Dance", code: "1DCE10", stage: "1" },
    { name: "Dance", code: "1DCE20", stage: "1" },
    { name: "Digital Communication Solutions", code: "1DCS10", stage: "1" },
    { name: "Digital Communication Solutions", code: "1DCS20", stage: "1" },
    { name: "Digital Technologies", code: "1DGT10", stage: "1" },
    { name: "Digital Technologies", code: "1DGT20", stage: "1" },
    { name: "Drama", code: "1DMA10", stage: "1" },
    { name: "Drama", code: "1DMA20", stage: "1" },
    { name: "Dutch (continuers)", code: "1DUC10", stage: "1" },
    { name: "Dutch (continuers)", code: "1DUC20", stage: "1" },
    { name: "English as an Additional Language", code: "1EAL10", stage: "1" },
    { name: "English as an Additional Language", code: "1EAL20", stage: "1" },
    { name: "Earth and Environmental Science", code: "1EES10", stage: "1" },
    { name: "Earth and Environmental Science", code: "1EES20", stage: "1" },
    { name: "Economics", code: "1ENO10", stage: "1" },
    { name: "Economics", code: "1ENO20", stage: "1" },
    { name: "English", code: "1ESH10", stage: "1" },
    { name: "English", code: "1ESH20", stage: "1" },
    { name: "Essential English", code: "1ETE10", stage: "1" },
    { name: "Essential English", code: "1ETE20", stage: "1" },
    { name: "Filipino (continuers)", code: "1FIC10", stage: "1" },
    { name: "Filipino (continuers)", code: "1FIC20", stage: "1" },
    { name: "Food and Hospitality", code: "1FOH10", stage: "1" },
    { name: "Food and Hospitality", code: "1FOH20", stage: "1" },
    { name: "French (beginners)", code: "1FRB10", stage: "1" },
    { name: "French (beginners)", code: "1FRB20", stage: "1" },
    { name: "French (continuers)", code: "1FRC10", stage: "1" },
    { name: "French (continuers)", code: "1FRC20", stage: "1" },
    { name: "German (beginners)", code: "1GEB10", stage: "1" },
    { name: "German (beginners)", code: "1GEB20", stage: "1" },
    { name: "German (continuers)", code: "1GEC10", stage: "1" },
    { name: "German (continuers)", code: "1GEC20", stage: "1" },
    { name: "Geography", code: "1GHY10", stage: "1" },
    { name: "Geography", code: "1GHY20", stage: "1" },
    { name: "Hebrew (continuers)", code: "1HBC10", stage: "1" },
    { name: "Hebrew (continuers)", code: "1HBC20", stage: "1" },
    { name: "Health and Wellbeing", code: "1HEW10", stage: "1" },
    { name: "Health and Wellbeing", code: "1HEW20", stage: "1" },
    { name: "Hindi (continuers)", code: "1HIC10", stage: "1" },
    { name: "Hindi (continuers)", code: "1HIC20", stage: "1" },
    { name: "Hungarian (continuers)", code: "1HUC10", stage: "1" },
    { name: "Hungarian (continuers)", code: "1HUC20", stage: "1" },
    { name: "Industry and Entrepreneurial Solutions", code: "1IES10", stage: "1" },
    { name: "Industry and Entrepreneurial Solutions", code: "1IES20", stage: "1" },
    { name: "Integrated Learning", code: "1ILN10", stage: "1" },
    { name: "Integrated Learning", code: "1ILN20", stage: "1" },
    { name: "Indonesian (beginners)", code: "1INB10", stage: "1" },
    { name: "Indonesian (beginners)", code: "1INB20", stage: "1" },
    { name: "Indonesian (continuers)", code: "1INC10", stage: "1" },
    { name: "Indonesian (continuers)", code: "1INC20", stage: "1" },
    { name: "Indonesian (background speakers)", code: "1IND10", stage: "1" },
    { name: "Indonesian (background speakers)", code: "1IND20", stage: "1" },
    { name: "Information Processing and Publishing", code: "1IPR10", stage: "1" },
    { name: "Information Processing and Publishing", code: "1IPR20", stage: "1" },
    { name: "Italian (beginners)", code: "1ITB10", stage: "1" },
    { name: "Italian (beginners)", code: "1ITB20", stage: "1" },
    { name: "Italian (continuers)", code: "1ITC10", stage: "1" },
    { name: "Italian (continuers)", code: "1ITC20", stage: "1" },
    { name: "Japanese (beginners)", code: "1JAB10", stage: "1" },
    { code: "2AAY10", name: "Arts and the Community", stage: 2 },
    { code: "2AAY20", name: "Arts and the Community", stage: 2 },
    { code: "2ABG20", name: "Aboriginal Studies", stage: 2 },
    { code: "2ACO20", name: "Accounting", stage: 2 },
    { code: "2ADA20", name: "Additional Language - Arrernte", stage: 2 },
    { code: "2ADE20", name: "Additional Language - Eastern Arrernte", stage: 2 },
    { code: "2ADL20", name: "Australian Languages - Additional Language", stage: 2 },
    { code: "2ADM20", name: "Additional Language - Martutjarr", stage: 2 },
    { code: "2ADO20", name: "Additional Language - Noongar", stage: 2 },
    { code: "2ADP20", name: "Additional Language - Pitjantjatjara", stage: 2 },
    { code: "2ADR20", name: "Additional Language - Anmatyerr", stage: 2 },
    { code: "2ADT20", name: "Additional Language - Pertrame", stage: 2 },
    { code: "2ADU20", name: "Additional Language - Pintupi/Luritja", stage: 2 },
    { code: "2ADW20", name: "Additional Language - Western Arrarnta", stage: 2 },
    { code: "2ADY20", name: "Additional Language - Alyawarr", stage: 2 },
    { code: "2AEC20", name: "Armenian (continuers)", stage: 2 },
    { code: "2AFL20", name: "Australian Languages - First Language", stage: 2 },
    { code: "2AFP20", name: "First Language - Pitjantjatjara", stage: 2 },
    { code: "2AFY20", name: "First Language - Yolngu", stage: 2 },
    { code: "2AGD20", name: "Agricultural Production", stage: 2 },
    { code: "2AGY20", name: "Agricultural Systems", stage: 2 },
    { code: "2AIF10", name: "Activating Identities and Futures", stage: 2 },
    { code: "2ANT20", name: "Ancient Studies", stage: 2 },
    { code: "2ARC20", name: "Arabic (continuers)", stage: 2 },
    { code: "2ARD20", name: "Revival Language - Adnyamathanha", stage: 2 },
    { code: "2ARG20", name: "Revival Language - Ngarrindjeri", stage: 2 },
    { code: "2ARL20", name: "Australian Languages - Revival Language", stage: 2 },
    { code: "2AUC20", name: "Auslan (continuers)", stage: 2 },
    { code: "2BEC20", name: "Bengali (continuers)", stage: 2 },
    { code: "2BGY20", name: "Biology", stage: 2 },
    { code: "2BNV20", name: "Business Innovation", stage: 2 },
    { code: "2BOC20", name: "Bosnian (continuers)", stage: 2 },
    { code: "2CAS10", name: "Creative Arts: Local Program", stage: 2 },
    { code: "2CAS20", name: "Creative Arts: Local Program", stage: 2 },
    { code: "2CAY10", name: "Communication and the Community", stage: 2 },
    { code: "2CAY20", name: "Communication and the Community", stage: 2 },
    { code: "2CEM20", name: "Chemistry", stage: 2 },
    { code: "2CHB20", name: "Chinese (beginners)", stage: 2 },
    { code: "2CHC20", name: "Chinese (continuers)", stage: 2 },
    { code: "2CHD20", name: "Chinese (background speakers)", stage: 2 },
    { code: "2CKC20", name: "Chin Hakha (continuers)", stage: 2 },
    { code: "2CRC20", name: "Croatian (continuers)", stage: 2 },
    { code: "2CSD10", name: "Child Studies", stage: 2 },
    { code: "2CSD20", name: "Child Studies", stage: 2 },
    { code: "2CSS10", name: "Cross-disciplinary Studies: Local Program", stage: 2 },
    { code: "2CSS20", name: "Cross-disciplinary Studies: Local Program", stage: 2 },
    { code: "2CVA10", name: "Creative Arts", stage: 2 },
    { code: "2CVA20", name: "Creative Arts", stage: 2 },
    { code: "2CXD10", name: "Cross-disciplinary Studies", stage: 2 },
    { code: "2CXD20", name: "Cross-disciplinary Studies", stage: 2 },
    { code: "2DCE20", name: "Dance", stage: 2 },
    { code: "2DCS20", name: "Digital Communication Solutions", stage: 2 },
    { code: "2DGT20", name: "Digital Technologies", stage: 2 },
    { code: "2DMA20", name: "Drama", stage: 2 },
    { code: "2DUC20", name: "Dutch (continuers)", stage: 2 },
    { code: "2EAL20", name: "English as an Additional Language", stage: 2 },
    { code: "2EES20", name: "Earth and Environmental Science", stage: 2 },
    { code: "2ELS20", name: "English Literary Studies", stage: 2 },
    { code: "2ENO20", name: "Economics", stage: 2 },
    { code: "2ESH20", name: "English", stage: 2 },
    { code: "2ETE20", name: "Essential English", stage: 2 },
    { code: "2FAY10", name: "Foods and the Community", stage: 2 },
    { code: "2FAY20", name: "Foods and the Community", stage: 2 },
    { code: "2FIC20", name: "Filipino (continuers)", stage: 2 },
    { code: "2FOH10", name: "Food and Hospitality", stage: 2 },
    { code: "2FOH20", name: "Food and Hospitality", stage: 2 },
    { code: "2FRB20", name: "French (beginners)", stage: 2 },
    { code: "2FRC20", name: "French (continuers)", stage: 2 },
    { code: "2GEB20", name: "German (beginners)", stage: 2 },
    { code: "2GEC20", name: "German (continuers)", stage: 2 },
    { code: "2GHY20", name: "Geography", stage: 2 },
    { code: "2HAY10", name: "Health, Recreation, and the Community", stage: 2 },
    { code: "2HAY20", name: "Health, Recreation, and the Community", stage: 2 },
    { code: "2HBC20", name: "Hebrew (continuers)", stage: 2 },
    { code: "2HEW20", name: "Health and Wellbeing", stage: 2 },
    { code: "2HIC20", name: "Hindi (continuers)", stage: 2 },
    { code: "2HSC10", name: "Humanities and Social Sciences Connections", stage: 2 },
    { code: "2HSC20", name: "Humanities and Social Sciences Connections", stage: 2 },
    { code: "2HUC20", name: "Hungarian (continuers)", stage: 2 },
    { code: "2ICA10", name: "Industry Connections A", stage: 2 },
    { code: "2ICA20", name: "Industry Connections A", stage: 2 },
    { code: "2ICB10", name: "Industry Connections B", stage: 2 },
    { code: "2ICB20", name: "Industry Connections B", stage: 2 },
    { code: "2ICC10", name: "Industry Connections C", stage: 2 },
    { code: "2ICC20", name: "Industry Connections C", stage: 2 },
    { code: "2IDC10", name: "Interdisciplinary Connections", stage: 2 },
    { code: "2IDC20", name: "Interdisciplinary Connections", stage: 2 }
  ];
console.log(subjects)
let selectedStage = 1
numberPicker.addEventListener('change', (event) => {
    selectedStage = event.target.value
  });

$(document).ready(function() {

$('#query').on('input', function(event) {
    event.preventDefault();
    const userInput = $('#query').val().toLowerCase(); 
    
        results = subjects.filter(item => item.name.toLowerCase().includes(userInput) && item.stage === selectedStage).slice(0,5);

    $('#results').empty();
    
    
    if (results.length > 0) {
        results.forEach((result, index) => {
            $('#results').append(`<li data-index="${index}">${result.name}</li>`); // Append each result description as a list item
        });
    } else {
        
        $('#results').append('<li>No results found</li>'); // Display a message when no results are found
        
    }
    
    
});

$('#results').on('click', 'li', function() {
    let index = $(this).data('index');
    let selectedItem = results[index]
    $('#query').val(selectedItem.description);
    $('#results').empty();
})
})
