const subjects = [
    { name: "Aboriginal Studies", stage: 1 },
    { name: "Accounting", stage: 1 },
    { name: "Australian Languages - Additional Language", stage: 1 },
    { name: "Armenian (continuers)", stage: 1 },
    { name: "Australian Languages - First Language", stage: 1 },
    { name: "Agriculture", stage: 1 },
    { name: "Albanian (continuers)", stage: 1 },
    { name: "Ancient Studies", stage: 1 },
    { name: "Arabic (continuers)", stage: 1 },
    { name: "Australian Languages - Revival Language", stage: 1 },
    { name: "Auslan (continuers)", stage: 1 },
    { name: "Bengali (continuers)", stage: 1 },
    { name: "Biology", stage: 1 },
    { name: "Business Innovation", stage: 1 },
    { name: "Bosnian (continuers)", stage: 1 },
    { name: "Chemistry", stage: 1 },
    { name: "Chinese (beginners)", stage: 1 },
    { name: "Chinese (continuers)", stage: 1 },
    { name: "Chinese (background speakers)", stage: 1 },
    { name: "Chin Hakha (continuers)", stage: 1 },
    { name: "Community Studies", stage: 1 },
    { name: "Croatian (continuers)", stage: 1 },
    { name: "Child Studies", stage: 1 },
    { name: "Creative Arts", stage: 1 },
    { name: "Cross-disciplinary Studies", stage: 1 },
    { name: "Dance", stage: 1 },
    { name: "Digital Communication Solutions", stage: 1 },
    { name: "Digital Technologies", stage: 1 },
    { name: "Drama", stage: 1 },
    { name: "Dutch (continuers)", stage: 1 },
    { name: "English as an Additional Language", stage: 1 },
    { name: "Earth and Environmental Science", stage: 1 },
    { name: "Economics", stage: 1 },
    { name: "English", stage: 1 },
    { name: "Essential English", stage: 1 },
    { name: "Filipino (continuers)", stage: 1 },
    { name: "Food and Hospitality", stage: 1 },
    { name: "French (beginners)", stage: 1 },
    { name: "French (continuers)", stage: 1 },
    { name: "German (beginners)", stage: 1 },
    { name: "German (continuers)", stage: 1 },
    { name: "Geography", stage: 1 },
    { name: "Hebrew (continuers)", stage: 1 },
    { name: "Health and Wellbeing", stage: 1 },
    { name: "Hindi (continuers)", stage: 1 },
    { name: "Hungarian (continuers)", stage: 1 },
    { name: "Industry and Entrepreneurial Solutions", stage: 1 },
    { name: "Integrated Learning", stage: 1 },
    { name: "Indonesian (beginners)", stage: 1 },
    { name: "Indonesian (continuers)", stage: 1 },
    { name: "Indonesian (background speakers)", stage: 1 },
    { name: "Information Processing and Publishing", stage: 1 },
    { name: "Digital Technologies", stage: 1 },
    { name: "Italian (beginners)", stage: 1 },
    { name: "Italian (continuers)", stage: 1 },
    { name: "Japanese (beginners)", stage: 1 },
    { name: "Japanese (continuers)", stage: 1 },
    { name: "Japanese (background speakers)", stage: 1 },
    { name: "Khmer (continuers)", stage: 1 },
    { name: "Korean (beginners)", stage: 1 },
    { name: "Korean (continuers)", stage: 1 },
    { name: "Korean (background speakers)", stage: 1 },
    { name: "Karen (continuers)", stage: 1 },
    { name: "Language and Culture", stage: 1 },
    { name: "Legal Studies", stage: 1 },
    { name: "Latin (continuers)", stage: 1 },
    { name: "Mathematics", stage: 1 },
    { name: "Essential Mathematics", stage: 1 },
    { name: "Media Studies", stage: 1 },
    { name: "Modern Greek (beginners)", stage: 1 },
    { name: "Modern Greek (continuers)", stage: 1 },
    { name: "General Mathematics", stage: 1 },
    { name: "Macedonian (continuers)", stage: 1 },
    { name: "Modern History", stage: 1 },
    { name: "Material Solutions", stage: 1 },
    { name: "Maltese (continuers)", stage: 1 },
    { name: "Music Advanced", stage: 1 },
    { name: "Music Experience", stage: 1 },
    { name: "Nepali (continuers)", stage: 1 },
    { name: "Nutrition", stage: 1 },
    { name: "Outdoor Education", stage: 1 },
    { name: "Portuguese (continuers)", stage: 1 },
    { name: "Physical Education", stage: 1 },
    { name: "Personal Learning Plan", stage: 1 },
    { name: "Persian (continuers)", stage: 1 },
    { name: "Polish (continuers)", stage: 1 },
    { name: "Politics, Power and People", stage: 1 },
    { name: "Philosophy", stage: 1 },
    { name: "Psychology", stage: 1 },
    { name: "Punjabi (continuers)", stage: 1 },
    { name: "Physics", stage: 1 },
    { name: "Religion Studies", stage: 1 },
    { name: "Robotic and Electronic Systems", stage: 1 },
    { name: "Romanian (continuers)", stage: 1 },
    { name: "Research Practices", stage: 1 },
    { name: "Russian (continuers)", stage: 1 },
    { name: "Russian (background speakers)", stage: 1 },
    { name: "Serbian (continuers)", stage: 1 },
    { name: "Sinhala (continuers)", stage: 1 },
    { name: "Society and Culture", stage: 1 },
    { name: "Spanish (beginners)", stage: 1 },
    { name: "Spanish (continuers)", stage: 1 },
    { name: "Spiritualities, Religion, and Meaning", stage: 1 },
    { name: "Scientific Studies", stage: 1 },
    { name: "Swedish (continuers)", stage: 1 },
    { name: "Tamil (continuers)", stage: 1 },
    { name: "Tourism", stage: 1 },
    { name: "Turkish (continuers)", stage: 1 },
    { name: "Visual Arts - Art", stage: 1 },
    { name: "Visual Arts - Design", stage: 1 },
    { name: "Vietnamese (continuers)", stage: 1 },
    { name: "Vietnamese (background speakers)", stage: 1 },
    { name: "Women's Studies", stage: 1 },
    { name: "Workplace Practices", stage: 1 },
    { name: "Yiddish (continuers)", stage: 1 },
    {name: "Arts and the Community", stage: 2},
    {name: "Aboriginal Studies", stage: 2},
    {name: "Accounting", stage: 2},
    {name: "Additional Language - Arrernte", stage: 2},
    {name: "Additional Language - Eastern Arrernte", stage: 2},
    {name: "Australian Languages - Additional Language", stage: 2},
    {name: "Additional Language - Martutjarr", stage: 2},
    {name: "Additional Language - Noongar", stage: 2},
    {name: "Additional Language - Pitjantjatjara", stage: 2},
    {name: "Additional Language - Anmatyerr", stage: 2},
    {name: "Additional Language - Pertrame", stage: 2},
    {name: "Additional Language - Pintupi/Luritja", stage: 2},
    {name: "Additional Language - Western Arrarnta", stage: 2},
    {name: "Additional Language - Alyawarr", stage: 2},
    {name: "Armenian (continuers)", stage: 2},
    {name: "Australian Languages - First Language", stage: 2},
    {name: "First Language - Pitjantjatjara", stage: 2},
    {name: "First Language - Yolngu", stage: 2},
    {name: "Agricultural Production", stage: 2},
    {name: "Agricultural Systems", stage: 2},
    {name: "Activating Identities and Futures", stage: 2},
    {name: "Ancient Studies", stage: 2},
    {name: "Arabic (continuers)", stage: 2},
    {name: "Revival Language - Adnyamathanha", stage: 2},
    {name: "Revival Language - Ngarrindjeri", stage: 2},
    {name: "Australian Languages - Revival Language", stage: 2},
    {name: "Auslan (continuers)", stage: 2},
    {name: "Bengali (continuers)", stage: 2},
    {name: "Biology", stage: 2},
    {name: "Business Innovation", stage: 2},
    {name: "Bosnian (continuers)", stage: 2},
    {name: "Creative Arts: Local Program", stage: 2},
    {name: "Communication and the Community", stage: 2},
    {name: "Chemistry", stage: 2},
    {name: "Chinese (beginners)", stage: 2},
    {name: "Chinese (continuers)", stage: 2},
    {name: "Chinese (background speakers)", stage: 2},
    {name: "Chin Hakha (continuers)", stage: 2},
    {name: "Croatian (continuers)", stage: 2},
    {name: "Child Studies", stage: 2},
    {name: "Cross-disciplinary Studies: Local Program", stage: 2},
    {name: "Creative Arts", stage: 2},
    {name: "Cross-disciplinary Studies", stage: 2},
    {name: "Dance", stage: 2},
    {name: "Digital Communication Solutions", stage: 2},
    {name: "Digital Technologies", stage: 2},
    {name: "Drama", stage: 2},
    {name: "Dutch (continuers)", stage: 2},
    {name: "English as an Additional Language", stage: 2},
    {name: "Earth and Environmental Science", stage: 2},
    {name: "English Literary Studies", stage: 2},
    {name: "Economics", stage: 2},
    {name: "English", stage: 2},
    {name: "Essential English", stage: 2},
    {name: "Foods and the Community", stage: 2},
    {name: "Food and Hospitality", stage: 2},
    {name: "French (beginners)", stage: 2},
    {name: "French (continuers)", stage: 2},
    {name: "German (beginners)", stage: 2},
    {name: "German (continuers)", stage: 2},
    {name: "Geography", stage: 2},
    {name: "Health, Recreation, and the Community", stage: 2},
    {name: "Hebrew (continuers)", stage: 2},
    {name: "Health and Wellbeing", stage: 2},
    {name: "Hindi (continuers)", stage: 2},
    {name: "Humanities and Social Sciences Connections", stage: 2},
    {name: "Industry Connections A", stage: 2},
    {name: "Industry Connections B", stage: 2},
    {name: "Industry Connections C", stage: 2},
    {name: "Interdisciplinary Connections", stage: 2},
    {name: "Industry and Entrepreneurial Solutions", stage: 2},
    {name: "Integrated Learning A", stage: 2},
    {name: "Integrated Learning B", stage: 2},
    {name: "Indonesian (beginners)", stage: 2},
    {name: "Indonesian (continuers)", stage: 2},
    {name: "Indonesian (background speakers)", stage: 2},
    {name: "Information Processing and Publishing", stage: 2},
    {name: "Italian (beginners)", stage: 2},
    {name: "Italian (continuers)", stage: 2},
    {name: "Japanese (beginners)", stage: 2},
    {name: "Japanese (continuers)", stage: 2},
    {name: "Japanese (background speakers)", stage: 2},
    {name: "Khmer (continuers)", stage: 2},
    {name: "Korean (beginners)", stage: 2},
    {name: "Korean (continuers)", stage: 2},
    {name: "Korean (background speakers)", stage: 2},
    {name: "Karen (continuers)", stage: 2},
    {name: "Language and Culture", stage: 2},
    {name: "Language and Culture: Local Program", stage: 2},
    {name: "Legal Studies", stage: 2},
    {name: "Latin (continuers)", stage: 2},
    {name: "Music Performance - Ensemble", stage: 2},
    {name: "Essential Mathematics", stage: 2},
    {name: "Media Studies", stage: 2},
    {name: "Music Explorations", stage: 2},
    {name: "Modern Greek (beginners)", stage: 2},
    {name: "Modern Greek (continuers)", stage: 2},
    {name: "General Mathematics", stage: 2},
    {name: "Mathematical Methods", stage: 2},
    {name: "Macedonian (continuers)", stage: 2},
    {name: "Modern History", stage: 2},
    {name: "Material Solutions", stage: 2},
    {name: "Specialist Mathematics", stage: 2},
    {name: "Music Studies", stage: 2},
    {name: "Music Performance - Solo", stage: 2},
    {name: "Science, Technology and the Community", stage: 2},
    {name: "Nepali (continuers)", stage: 2},
    {name: "Nutrition", stage: 2},
    {name: "Outdoor Education", stage: 2},
    {name: "Portuguese (continuers)", stage: 2},
    {name: "Physical Education", stage: 2},
    {name: "Persian (continuers)", stage: 2},
    {name: "Polish (continuers)", stage: 2},
    {name: "Politics, Power and People", stage: 2},
    {name: "Philosophy", stage: 2},
    {name: "Practical Connections", stage: 2},
    {name: "Psychology", stage: 2},
    {name: "Punjabi (continuers)", stage: 2},
    {name: "Physics", stage: 2},
    {name: "Robotic and Electronic Systems", stage: 2},
    {name: "Romanian (continuers)", stage: 2},
    {name: "Research Project A", stage: 2},
    {name: "Research Project B", stage: 2},
    {name: "Russian (continuers)", stage: 2},
    {name: "Society and Culture: Local Program", stage: 2},
    {name: "Serbian (continuers)", stage: 2},
    {name: "Sinhala (continuers)", stage: 2},
    {name: "Spanish (beginners)", stage: 2},
    {name: "Spanish (continuers)", stage: 2},
    {name: "Spiritualities, Religion, and Meaning", stage: 2},
    {name: "STEM Connections", stage: 2},
    {name: "Scientific Studies", stage: 2},
    {name: "Swedish (continuers)", stage: 2},
    {name: "Tamil (continuers)", stage: 2},
    {name: "Tourism", stage: 2},
    {name: "Turkish (continuers)", stage: 2},
    {name: "Visual Arts - Art", stage: 2},
    {name: "Visual Arts - Design", stage: 2},
    {name: "Vietnamese (continuers)", stage: 2},
    {name: "Vietnamese (background speakers)", stage: 2},
    {name: "Work and the Community", stage: 2},
    {name: "Women's Studies", stage: 2},
    {name: "Workplace Practices A", stage: 2},
    {name: "Workplace Practices B", stage: 2},
    {name: "Workplace Practices", stage: 2},
    {name: "Yiddish (continuers)", stage: 2}
  ];
console.log(subjects)
let selectedStage = 1
numberPicker.addEventListener('change', (event) => {
    selectedStage = event.target.value
    console.log(selectedStage)
  });

$(document).ready(function() {

$('#query').on('input', function(event) {
    event.preventDefault();
    const userInput = $('#query').val().toLowerCase(); 
    
        results = subjects.filter(item => item.name.toLowerCase().includes(userInput) && item.stage.toFixed(1) === selectedStage).slice(0,5);

    $('#results').empty();
    
    
    if (results.length > 0) {
        results.forEach((result, index) => {
            $('#results').append(`<li data-index="${index}">${result.name}</li>`);

        });
    } else {
        
        $('#results').append('<li>No results found</li>'); // Display a message when no results are found
        
    }
    
    
});

$('#results').on('click', 'li', function() {
    let index = $(this).data('index');
    let selectedItem = results[index]
    $('#query').val(selectedItem.name);
    $('#results').empty();
})
})
